# Generated by Django 4.1.3 on 2022-11-08 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ('category_name',), 'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='organizations',
            options={'ordering': ('organization_name',), 'verbose_name': 'организация', 'verbose_name_plural': 'организации'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('amount',), 'verbose_name': 'транзакция', 'verbose_name_plural': 'транзакции'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='category_name',
            field=models.CharField(max_length=60, unique=True, verbose_name='Имя категории'),
        ),
        migrations.AlterModelTable(
            name='categories',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='organizations',
            table='organizations',
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='transactions',
        ),
    ]
