# Generated by Django 4.1.3 on 2022-11-08 21:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_alter_categories_options_alter_organizations_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date_of_payment',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 8, 21, 48, 2, 473556, tzinfo=datetime.timezone.utc), verbose_name='время транзакции'),
        ),
    ]
