# Generated by Django 4.1.3 on 2022-11-08 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_alter_transaction_date_of_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('date_of_payment', 'amount'), 'verbose_name': 'транзакция', 'verbose_name_plural': 'транзакции'},
        ),
    ]
